# ===----------------------------------------------------------------------=== #
# Copyright (c) 2026, Modular Inc. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===----------------------------------------------------------------------=== #
"""Configuration for Parakeet-TDT models.

Extends the shared ``ParakeetConfigBase`` with TDT-specific decoder, joint,
and duration properties. Reads from a config.json generated by
``scripts/convert_nemo.py``.
"""

from __future__ import annotations

from dataclasses import dataclass
from types import SimpleNamespace

from ..parakeet.config_base import ParakeetConfigBase


@dataclass(kw_only=True)
class TDTModelConfig(ParakeetConfigBase):
    """Configuration for Parakeet-TDT models.

    Inherits all encoder properties from ``ParakeetConfigBase``.
    TDT overrides ``blank_id`` (= vocab_size, not vocab_size - 1)
    and ``attention_bias``/``convolution_bias`` defaults (False).
    """

    # --- Override defaults from base ---

    @property
    def attention_bias(self) -> bool:
        return getattr(self.encoder_config, "attention_bias", False)

    @property
    def convolution_bias(self) -> bool:
        return getattr(self.encoder_config, "convolution_bias", False)

    @property
    def blank_id(self) -> int:
        return self.vocab_size

    # --- TDT-specific properties ---

    @property
    def decoder_config(self) -> SimpleNamespace:
        """Decoder config, converting from dict if needed."""
        dc = self.huggingface_config.decoder_config
        if isinstance(dc, dict):
            return SimpleNamespace(**dc)
        return dc

    @property
    def joint_config(self) -> SimpleNamespace:
        """Joint config, converting from dict if needed."""
        jc = self.huggingface_config.joint_config
        if isinstance(jc, dict):
            return SimpleNamespace(**jc)
        return jc

    @property
    def pred_hidden(self) -> int:
        return self.decoder_config.pred_hidden

    @property
    def pred_rnn_layers(self) -> int:
        return self.decoder_config.pred_rnn_layers

    @property
    def joint_hidden(self) -> int:
        return self.joint_config.joint_hidden

    @property
    def tdt_durations(self) -> list[int]:
        return self.huggingface_config.tdt_durations

    @property
    def normalize_features(self) -> str | None:
        """Feature normalization mode from NeMo preprocessor config."""
        return getattr(self.huggingface_config, "normalize_features", None)
